---
- name: Deploy roles
  hosts: lo
  become: true

  tasks:
    - name: Copy monitoring
      ansible.builtin.copy:
        src: ../monitoring
        dest: /tmp
        mode: "0666"

    - name: Copy app
      ansible.builtin.copy:
        src: ../app
        dest: /tmp
        mode: "0666"

    - name: Run monitoring docker-compose
      community.docker.docker_compose:
        project_src: /tmp/monitoring/
        build: true

    - name: Run app docker-compose
      community.docker.docker_compose:
        project_src: /tmp/app/
        build: true
